**Practicaremos lo aprendido de matplotlib**

In [2]:
#Importar la librerias pandas, matplotlib y numpy
import matplotlib.pyplot as plt
import pandas as pd
import os
# Ver ruta actual
os.chdir(r"C:\Users\monti.UNITY12\OneDrive\Documentos\Curso Python 2026")

In [6]:

#Importar un archivo csv llamado accidentes.csv
df = pd.read_csv("accidentes.csv", index_col='NumeroCaso')
df

,Estado,NombreEstado,Peatones,Personas _no_vehiculos,Vehiculos automotores,VehiculosEstacionados,Condado,NombreCondado,Ciudad,NombreCiudad,...,Clima,Autobus Escolar,Cruce de Trenes,Hora Notificacion,Minuto Notificacion,Hora Llegada,Minuto Llegada,Decesos,Fecha,PersonaVehiculo
NumeroCaso,,,,,,,,,,,,,,,,,,,,,
10001,1,Alabama,0,0,2,0,107,PICKENS (107),0,NO APLICA,...,Despejado,No,NO APLICA,12,47,13,4,1,01/01/2022,3
10002,1,Alabama,0,0,2,0,101,MONTGOMERY (101),0,NO APLICA,...,Despejado,No,NO APLICA,99,99,99,99,2,01/01/2022,5
10003,1,Alabama,0,0,1,0,115,ST. CLAIR (115),0,NO APLICA,...,Nublado,No,NO APLICA,1,33,1,50,1,01/01/2022,2
10004,1,Alabama,0,0,1,0,101,MONTGOMERY (101),0,NO APLICA,...,Nublado,No,NO APLICA,14,48,15,9,1,02/01/2022,1
10005,1,Alabama,1,1,1,0,73,JEFFERSON (73),0,NO APLICA,...,lluvia,No,NO APLICA,18,48,18,54,1,02/01/2022,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560114,56,Wyoming,0,0,2,0,37,SWEETWATER (37),730,ROCK SPRINGS,...,Despejado,No,NO APLICA,11,30,11,35,1,27/12/2022,2
560115,56,Wyoming,0,0,1,0,23,LINCOLN (23),0,NO APLICA,...,Nieve,No,NO APLICA,99,98,99,98,1,24/10/2022,1
560116,56,Wyoming,0,0,1,0,21,LARAMIE (21),100,CHEYENNE,...,Nieve,No,NO APLICA,15,2,15,7,1,21/12/2022,1
560117,56,Wyoming,0,0,1,0,19,JOHNSON (19),0,NO APLICA,...,Nieve,No,NO APLICA,7,24,7,40,1,22/12/2022,1
560118,56,Wyoming,0,0,1,0,21,LARAMIE (21),0,NO APLICA,...,Despejado,No,NO APLICA,5,6,5,25,1,17/12/2022,4

In [7]:
#Mostrar los primeros elementos
df.head()

,Estado,NombreEstado,Peatones,Personas _no_vehiculos,Vehiculos automotores,VehiculosEstacionados,Condado,NombreCondado,Ciudad,NombreCiudad,...,Clima,Autobus Escolar,Cruce de Trenes,Hora Notificacion,Minuto Notificacion,Hora Llegada,Minuto Llegada,Decesos,Fecha,PersonaVehiculo
NumeroCaso,,,,,,,,,,,,,,,,,,,,,
10001,1,Alabama,0,0,2,0,107,PICKENS (107),0,NO APLICA,...,Despejado,No,NO APLICA,12,47,13,4,1,01/01/2022,3
10002,1,Alabama,0,0,2,0,101,MONTGOMERY (101),0,NO APLICA,...,Despejado,No,NO APLICA,99,99,99,99,2,01/01/2022,5
10003,1,Alabama,0,0,1,0,115,ST. CLAIR (115),0,NO APLICA,...,Nublado,No,NO APLICA,1,33,1,50,1,01/01/2022,2
10004,1,Alabama,0,0,1,0,101,MONTGOMERY (101),0,NO APLICA,...,Nublado,No,NO APLICA,14,48,15,9,1,02/01/2022,1
10005,1,Alabama,1,1,1,0,73,JEFFERSON (73),0,NO APLICA,...,lluvia,No,NO APLICA,18,48,18,54,1,02/01/2022,1