In [217]:
#Importar la libreria de pandas
import pandas as pd
import os
os.chdir(r'C:\Users\monti.UNITY12\OneDrive\Documentos\Curso Python 2026')
df = pd.read_csv('accidentes.csv', index_col='NumeroCaso')
Limpiado = df.dropna()
Limpiado
Limpiado.groupby('NombreCiudad').get_group('CODY')#Filtrar datos por grupos de una columna

,Estado,NombreEstado,Peatones,Personas _no_vehiculos,Vehiculos automotores,VehiculosEstacionados,Condado,NombreCondado,Ciudad,NombreCiudad,...,Clima,Autobus Escolar,Cruce de Trenes,Hora Notificacion,Minuto Notificacion,Hora Llegada,Minuto Llegada,Decesos,Fecha,PersonaVehiculo
NumeroCaso,,,,,,,,,,,,,,,,,,,,,
560052,56,Wyoming,0.0,0.0,2,0,29,PARK (29),130,CODY,...,Nublado,No,NO APLICA,12,21,12,27,1,02/08/2022,6
560103,56,Wyoming,0.0,0.0,2,0,29,PARK (29),130,CODY,...,Despejado,No,NO APLICA,9,42,9,45,1,19/11/2022,3

**Que es pandas**

¡Claro! Pandas es una biblioteca de Python muy popular utilizada para análisis y manipulación de datos. 
Si tienes una pregunta específica sobre Pandas, como cómo usar una función, cómo leer un archivo Excel o CSV, o cómo filtrar o agrupar datos, dime y con gusto te ayudo.
**¿Por qué utilizar Pandas?**

Pandas nos permite analizar grandes datos y sacar conclusiones basadas en teorías estadísticas.
Pandas puede limpiar conjuntos de datos desordenados y hacerlos legibles y relevantes.
Los datos relevantes son muy importantes en la ciencia de datos.

**🔧 Características principales**

DataFrame: estructura bidimensional (como una hoja de Excel) con etiquetas en filas y columnas.

Series: estructura unidimensional, como una columna de datos.

Lectura de datos: desde CSV, Excel, JSON, SQL, etc.

Filtrado y selección: accede a datos específicos con condiciones.

Agrupación y agregación: ideal para análisis estadístico.

Visualización: se integra con Matplotlib para crear gráficos.

In [218]:
#Crear unas series de pandas llamada persona, que contenga el nombre y la edades
"""persona = pd.Series(['Mateo', 23], index=['Nombre', 'Edad'])
persona"""#forma 1
#forma 2
nombres = ['Salome', 'Victoria', 'Manuel', 'Jessica']
edades = [23, 22, 24, 28]

In [219]:
#Covertirlo a series
personas = pd.Series(edades, index=nombres)
personas

Salome      23
Victoria    22
Manuel      24
Jessica     28
dtype: int64

In [220]:
#Acceder a los valores
personas['Manuel']

np.int64(24)

In [221]:
#Mostrar los valores
personas.values

array([23, 22, 24, 28])

In [222]:
#Mostrar los nombres
personas.index

Index(['Salome', 'Victoria', 'Manuel', 'Jessica'], dtype='object')

In [223]:
#Imprimir elementos
personas.head(2)

Salome      23
Victoria    22
dtype: int64

In [224]:
#Mostrar ultimos elementos
personas.tail(2)

Manuel     24
Jessica    28
dtype: int64

In [225]:
#Ordenar los valores
personas.sort_values()

Victoria    22
Salome      23
Manuel      24
Jessica     28
dtype: int64

In [226]:
#ordenar por nombres
personas.sort_index()

Jessica     28
Manuel      24
Salome      23
Victoria    22
dtype: int64

In [227]:
#convertir cadenas de textos a fechas
fechas = ["2023-10-1", "2024-11-12"]

In [228]:
#convertir a fechas
cumpleaños = pd.to_datetime(fechas)
cumpleaños

DatetimeIndex(['2023-10-01', '2024-11-12'], dtype='datetime64[ns]', freq=None)

In [229]:
#Mostrar solo los meses
cumpleaños.month

Index([10, 11], dtype='int32')

In [230]:
#Mostrar solos los años
cumpleaños.year

Index([2023, 2024], dtype='int32')

In [231]:
#Mostraar solos los dias
cumpleaños.dayofweek

Index([6, 1], dtype='int32')

In [232]:
#Formatear cada fecha en la serie cumpleaños al formato "mm/dd/yy"
cumpleaños.strftime("%m/%d/%y")

Index(['10/01/23', '11/12/24'], dtype='object')

**Crear un dataframe de una lista de diccionario, estableciendo las columnas.**

In [233]:
#Crear mi lista de diccionario
futbolista = [{'id':1, 'nombre':'Mariana', 'horas_entrenadas': 20, 'posicion': 'delantero', 'liga':1},
              {'id':2, 'nombre':'SoL', 'horas_entrenadas': 10, 'posicion': 'delantero', 'liga':2},
              {'id':3, 'nombre':'Mar', 'horas_entrenadas': 1, 'posicion': 'defensa', 'liga':1},
              {'id':4, 'nombre':'Ofelia', 'horas_entrenadas': 12, 'posicion': 'delantero', 'liga':3},
              {'id':5, 'nombre':'Camila', 'horas_entrenadas': 11, 'posicion': 'portero', 'liga':1}]

In [234]:
#Crear el dataframe para verlo en tabla.
futbolista = pd.DataFrame(futbolista).set_index('id')
futbolista

     nombre  horas_entrenadas   posicion  liga
id
1   Mariana                20  delantero     1
2       SoL                10  delantero     2
3       Mar                 1    defensa     1
4    Ofelia                12  delantero     3
5    Camila                11    portero     1

In [235]:
#seleccionar columnas nombre y posicion del dataframe.
#acceder a la informacion de 1 columna.
futbolista[['nombre']]

     nombre
id
1   Mariana
2       SoL
3       Mar
4    Ofelia
5    Camila

In [236]:
#mostrar mas columnas
futbolista[['nombre', 'posicion']]

     nombre   posicion
id
1   Mariana  delantero
2       SoL  delantero
3       Mar    defensa
4    Ofelia  delantero
5    Camila    portero

In [237]:
#seleccionar filas del dataframe.
futbolista.loc[[2, 3]]

   nombre  horas_entrenadas   posicion  liga
id
2     SoL                10  delantero     2
3     Mar                 1    defensa     1

In [238]:
#seleccionar filas del dataframe y mostrar solo las columnas seleccionadas.
futbolista.loc[[2, 3],['nombre', 'posicion']]

   nombre   posicion
id
2     SoL  delantero
3     Mar    defensa

In [239]:
#Seleccionar las filas en las posiciones, y las columnas por posiciones.
futbolista.iloc[[0, 3], [3]]

    liga
id
1      1
4      3

In [240]:
#realizar cAlculos del promedio de las horas, agrupado por la columna posicion.
futbolista.groupby('posicion')['horas_entrenadas'].mean()

posicion
defensa       1.0
delantero    14.0
portero      11.0
Name: horas_entrenadas, dtype: float64

In [241]:
#Crear mi primera tabla dinamica
futbolista.pivot_table(index = 'posicion', values = ['horas_entrenadas'], columns = 'liga', aggfunc='max')

          horas_entrenadas
liga                     1     2     3
posicion
defensa                1.0   NaN   NaN
delantero             20.0  10.0  12.0
portero               11.0   NaN   NaN

In [242]:
data = pd.DataFrame([['María', 18], ['Luis', 22], ['Carmen', 20]], columns=['Nombre', 'Edad'])
data.set_index('Edad')

      Nombre
Edad
18     María
22      Luis
20    Carmen

In [243]:
#Eliminar filas
data.drop(1)

   Nombre  Edad
0   María    18
2  Carmen    20

In [244]:
from math import log
data['Edad'].apply(log)

0    2.890372
1    3.091042
2    2.995732
Name: Edad, dtype: float64

In [245]:
#Filtrar informacion por grupos de una sola columna{}
futbolista.groupby('posicion').get_group('delantero')

     nombre  horas_entrenadas   posicion  liga
id
1   Mariana                20  delantero     1
2       SoL                10  delantero     2
4    Ofelia                12  delantero     3

In [246]:
import numpy as np
#Promedio de horas entrenadas por posicion
futbolista.groupby('posicion')['horas_entrenadas'].mean().reset_index()

    posicion  horas_entrenadas
0    defensa               1.0
1  delantero              14.0
2    portero              11.0

In [247]:
datos = {'nombre':['María', 'Luis', 'Carmen'],
'edad':[18, 22, 20],
'Matemáticas':[8.5, 7, 3.5],
'Economía':[8, 6.5, 5],
'Programación':[6.5, 4, 9]}
df = pd.DataFrame(datos)
df1 = df.melt(id_vars=['nombre', 'edad'], var_name='asignatura', value_name='nota')
df1

   nombre  edad    asignatura  nota
0   María    18   Matemáticas   8.5
1    Luis    22   Matemáticas   7.0
2  Carmen    20   Matemáticas   3.5
3   María    18      Economía   8.0
4    Luis    22      Economía   6.5
5  Carmen    20      Economía   5.0
6   María    18  Programación   6.5
7    Luis    22  Programación   4.0
8  Carmen    20  Programación   9.0

In [248]:
df1.pivot(index='nombre', columns='asignatura', values='nota')

asignatura  Economía  Matemáticas  Programación
nombre
Carmen           5.0          3.5           9.0
Luis             6.5          7.0           4.0
María            8.0          8.5           6.5

In [249]:
df1 = pd.DataFrame({"Nombre":["Carmen", "Luis"], 
 "Sexo":["Mujer", "Hombre"], 
 "Edad":[22, 18]}).set_index("Nombre")
df2 = pd.DataFrame({"Nombre":["María", "Pedro"], 
"Sexo":["Mujer", "Hombre"], 
"Edad":[25, 30]}).set_index("Nombre")
combinado = pd.concat([df1, df2])
combinado

          Sexo  Edad
Nombre
Carmen   Mujer    22
Luis    Hombre    18
María    Mujer    25
Pedro   Hombre    30

In [250]:
dx1 = pd.DataFrame({'Nombre':['Mar', 'Ana', 'Marco'],
                   'Sexo':['M','M', 'H']}).set_index('Nombre')

dx2 = pd.DataFrame({
    'Nombre': ['Mar', 'Ana', 'Marco'],
    'Edad': [22, 19, 33]}).set_index('Nombre')
unido = pd.concat([dx1, dx2], axis=1)
unido

       Sexo  Edad
Nombre
Mar       M    22
Ana       M    19
Marco     H    33

In [257]:
dp1 = pd.DataFrame({
    "Nombre":["Carmen", "Luis", "María"],  
    "Sexo":["Mujer", "Hombre", "Mujer"]
    })

dp2 = pd.DataFrame({
    "Nombre":["María", "Pedro", "Luis"], 
    "Edad":[25, 30, 18]})
mezcla1 = pd.merge(dp1, dp2, on="Nombre", how='right')
mezcla1#

  Nombre    Sexo  Edad
0  María   Mujer    25
1  Pedro     NaN    30
2   Luis  Hombre    18