In [1]:
#Importar la libreria de pandas
import pandas as pd

**Que es pandas**

¡Claro! Pandas es una biblioteca de Python muy popular utilizada para análisis y manipulación de datos. 
Si tienes una pregunta específica sobre Pandas, como cómo usar una función, cómo leer un archivo Excel o CSV, o cómo filtrar o agrupar datos, dime y con gusto te ayudo.
**¿Por qué utilizar Pandas?**

Pandas nos permite analizar grandes datos y sacar conclusiones basadas en teorías estadísticas.
Pandas puede limpiar conjuntos de datos desordenados y hacerlos legibles y relevantes.
Los datos relevantes son muy importantes en la ciencia de datos.

**🔧 Características principales**

DataFrame: estructura bidimensional (como una hoja de Excel) con etiquetas en filas y columnas.

Series: estructura unidimensional, como una columna de datos.

Lectura de datos: desde CSV, Excel, JSON, SQL, etc.

Filtrado y selección: accede a datos específicos con condiciones.

Agrupación y agregación: ideal para análisis estadístico.

Visualización: se integra con Matplotlib para crear gráficos.

In [2]:
#Crear unas series de pandas llamada persona, que contenga el nombre y la edades
"""persona = pd.Series(['Mateo', 23], index=['Nombre', 'Edad'])
persona"""#forma 1
#forma 2
nombres = ['Salome', 'Victoria', 'Manuel', 'Jessica']
edades = [23, 22, 24, 28]

In [3]:
#Covertirlo a series
personas = pd.Series(edades, index=nombres)
personas

Salome      23
Victoria    22
Manuel      24
Jessica     28
dtype: int64

In [4]:
#Acceder a los valores
personas['Manuel']

np.int64(24)

In [5]:
#Mostrar los valores
personas.values

array([23, 22, 24, 28])

In [6]:
#Mostrar los nombres
personas.index

Index(['Salome', 'Victoria', 'Manuel', 'Jessica'], dtype='object')

In [7]:
#Imprimir elementos
personas.head(2)

Salome      23
Victoria    22
dtype: int64

In [8]:
#Mostrar ultimos elementos
personas.tail(2)

Manuel     24
Jessica    28
dtype: int64

In [9]:
#Ordenar los valores
personas.sort_values()

Victoria    22
Salome      23
Manuel      24
Jessica     28
dtype: int64

In [10]:
#ordenar por nombres
personas.sort_index()

Jessica     28
Manuel      24
Salome      23
Victoria    22
dtype: int64

In [11]:
#convertir cadenas de textos a fechas
fechas = ["2023-10-1", "2024-11-12"]

In [12]:
#convertir a fechas
cumpleaños = pd.to_datetime(fechas)
cumpleaños

DatetimeIndex(['2023-10-01', '2024-11-12'], dtype='datetime64[ns]', freq=None)

In [13]:
#Mostrar solo los meses
cumpleaños.month

Index([10, 11], dtype='int32')

In [14]:
#Mostrar solos los años
cumpleaños.year

Index([2023, 2024], dtype='int32')

In [16]:
#Mostraar solos los dias
cumpleaños.dayofweek

Index([6, 1], dtype='int32')

In [18]:
#Formatear cada fecha en la serie cumpleaños al formato "mm/dd/yy"
cumpleaños.strftime("%m/%d/%y")

Index(['10/01/23', '11/12/24'], dtype='object')

**Crear un dataframe de una lista de diccionario, estableciendo las columnas.**

In [28]:
#Crear mi lista de diccionario
futbolista = [{'id':1, 'nombre':'Mariana', 'horas_entrenadas': 20, 'posicion': 'delantero', 'liga':1},
              {'id':2, 'nombre':'SoL', 'horas_entrenadas': 10, 'posicion': 'delantero', 'liga':2},
              {'id':3, 'nombre':'Mar', 'horas_entrenadas': 1, 'posicion': 'defensa', 'liga':1},
              {'id':4, 'nombre':'Ofelia', 'horas_entrenadas': 12, 'posicion': 'delantero', 'liga':3},
              {'id':5, 'nombre':'Camila', 'horas_entrenadas': 11, 'posicion': 'portero', 'liga':1}]

In [29]:
#Crear el dataframe para verlo en tabla.
futbolista = pd.DataFrame(futbolista).set_index('id')
futbolista

     nombre  horas_entrenadas   posicion  liga
id
1   Mariana                20  delantero     1
2       SoL                10  delantero     2
3       Mar                 1    defensa     1
4    Ofelia                12  delantero     3
5    Camila                11    portero     1

In [30]:
#seleccionar columnas nombre y posicion del dataframe.
#acceder a la informacion de 1 columna.
futbolista[['nombre']]

     nombre
id
1   Mariana
2       SoL
3       Mar
4    Ofelia
5    Camila

In [31]:
#mostrar mas columnas
futbolista[['nombre', 'posicion']]

     nombre   posicion
id
1   Mariana  delantero
2       SoL  delantero
3       Mar    defensa
4    Ofelia  delantero
5    Camila    portero

In [32]:
#seleccionar filas del dataframe.
futbolista.loc[[2, 3]]

   nombre  horas_entrenadas   posicion  liga
id
2     SoL                10  delantero     2
3     Mar                 1    defensa     1

In [ ]:
#seleccionar filas del dataframe y mostrar solo las columnas seleccionadas.
futbolista.loc[[2, 3],['nombre', 'posicion']]

   nombre   posicion
id
2     SoL  delantero
3     Mar    defensa

In [40]:
#Seleccionar las filas en las posiciones, y las columnas por posiciones.
futbolista.iloc[[0, 3], [1]]

    horas_entrenadas
id
1                 20
4                 12

In [50]:
#realizar cAlculos del promedio de las horas, agrupado por la columna posicion.
futbolista.groupby('posicion')['horas_entrenadas'].mean()

posicion
defensa       1.0
delantero    14.0
portero      11.0
Name: horas_entrenadas, dtype: float64

In [49]:
#Crear mi primera tabla dinamica
futbolista.pivot_table(index = 'posicion', values = ['horas_entrenadas'], columns = 'liga', aggfunc='max')

          horas_entrenadas
liga                     1     2     3
posicion
defensa                1.0   NaN   NaN
delantero             20.0  10.0  12.0
portero               11.0   NaN   NaN